version: '3.9'

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hai-bca
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: